version: '3'

services:
  # nexus3
  nexus:
    image: sonatype/nexus3:latest
    container_name: compose_nexus
    restart: always
    volumes:
      - {$HOME}/data/nexus:/nexus-data
    ports:
      - 8081:8081
  # gitlab
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: compose_gitlab
    restart: always
    hostname: 192.168.2.240
    environment:
      GITLAB_OMNIBUS_CONFIG:
        external_url 'http://192.168.2.240'
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - {$HOME}/data/gitlab/config:/etc/gitlab
      - {$HOME}/data/gitlab/logs:/var/log/gitlab
      - {$HOME}/data/gitlab/data:/var/opt/gitlab
    ports:
      - 80:80
      - 443:443
      - 32:22
  # apache http server
  httpd:
    image: httpd:latest
    container_name: compose_httpd
    restart: always
    volumes:
      - {$HOME}/data/apache-httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - {$HOME}/data/apache-httpd/htdocs/:/usr/local/apache2/htdocs/
      - {$HOME}/data/apache-httpd/logs/:/usr/local/apache2/logs/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:80
  # jenkins
  jenkins:
    image: jenkins/jenkins:latest
    container_name: compose_jenkins
    restart: always
    volumes:
      - {$HOME}/data/jenkins/home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
  # registry
  registry:
    image: registry:latest
    container_name: compose_registry
    restart: always
    volumes:
      - {$HOME}/data/registry/:/var/lib/registry
    ports:
      - 5000:5000
